Iter13
akashipov/MetricCollector pull request #14
Opened 2023-11-15 16:24 UTC by akashipov

2023-11-16 09:15 UTC, edylcrm requested changes

2023-11-16 09:15 UTC, edylcrm commented on internal/server/storages.go
> +func (r *MemStorage) Record(
[BLOCKER] структура судя по названию отвечает за хранение данных в памяти, но тут еще и psql появился. Давай сделаем для psql отдельную структуру и где нужно использовать storage использовать interface т.е. должно получиться как-то так:
```
type Storage interface {
    Get(ctx context.Context, metricName string) (string, error)
    Record(ctx context.Context, value *general.Metrics) error
}
```
И две структуры MemStorage и PsqlStorage которые этот интерфейс будут реализованы

2023-11-18 19:54 UTC, akashipov commented on internal/server/storages.go
> +func (r *MemStorage) Record(
А да, так наверное будет логичнее.... а то каждый раз метод будет расширяться и расширяться, слишком сложным станет

2023-11-20 08:37 UTC, edylcrm approved these changes

2023-11-24 00:56 UTC, merged