Iter5: added possibility to work with env variables
akashipov/MetricCollector pull request #5
Opened 2023-10-09 01:36 UTC by akashipov

https://practicum.yandex.ru/learn/go-advanced/courses/fe725b51-a888-4c0a-809a-611a1ef8e2ba/sprints/139864/topics/4a8fcda9-29f1-43e5-87d8-ea21f505ab00/lessons/9f871c8a-e3d0-4d83-a3f0-41ac1c449e29/

2023-10-15 11:33 UTC, edylcrm requested changes

2023-10-15 19:05 UTC, akashipov commented on internal/storages.go
> +	fmt.Stringer
По моему я это использовал до этого, чтобы выводить в аутпут или в файл. Потом появился вывод на главной странице и я это убрал. Можно убрать в принципе

2023-10-15 19:05 UTC, akashipov commented on internal/handlers.go
> +	if MetricType == GAUGE {
Да, все ок. Спасибо за замечания даже в этом плане, я поправлю

2023-10-15 20:07 UTC, akashipov commented on internal/handlers.go
> +	if MetricType == GAUGE {
@edylcrm  а что значит унес куда нибудь в сервис? просто в отдельный файл в другом месте?

2023-10-15 20:36 UTC, akashipov commented on internal/storages.go
> +	fmt.Stringer
а, это используется в тестах

2023-10-15 20:37 UTC, akashipov commented on internal/storages.go
> +	fmt.Stringer
а, да. тут я путаюсь иногда и добавляю зачем то это туда

2023-10-15 20:40 UTC, akashipov commented on internal/storages.go
> +		s += fmt.Sprintf("key: %s -> value: %v\n", k, v.GetValue())
честно говоря я не очень понял что тут имеется в виду

2023-10-15 20:47 UTC, akashipov commented on internal/metrics.go
> +func NewCounter(v *int64) *Counter {
поправил

2023-10-15 22:37 UTC, akashipov commented on internal/metric_senders.go
> +	for i := 0; i >= 0; i++ {
поправил

2023-10-15 22:38 UTC, akashipov commented on internal/handlers.go
> +		if MapMetric.m == nil {
поправил

2023-10-15 22:39 UTC, akashipov commented on cmd/agent/main.go
> +	a := internal.MetricSender{
сделал

2023-10-15 22:40 UTC, akashipov commented on cmd/server/main.go
> +	return http.ListenAndServe(*internal.HPServer, internal.ServerRouter())
тут если честно как то сложно... попробую разобраться

2023-10-16 06:29 UTC, edylcrm commented on internal/handlers.go
> +	if MetricType == GAUGE {
Ага, в отдельный файл

2023-10-16 11:45 UTC, akashipov commented on internal/metrics.go
> +func (r *Counter) GetValue() interface{} {
а, я сделал это чтобы следовать интерфейсу выше видимо. если можно использовать int64 то поправлю тогда

2023-10-17 08:01 UTC, edylcrm requested changes

2023-10-17 08:01 UTC, edylcrm commented on internal/server/handlers.go
> +		defer func() {
**[LINT]** а зачем это делать через defer? Выглядит не очень красиво.

2023-10-17 08:01 UTC, edylcrm commented on internal/server/handlers.go
> +		panic(fmt.Sprintf("%s: %v", err.Error(), status))
**[BLOCKER]** убрать использование паники

2023-10-17 08:01 UTC, edylcrm commented on internal/server/handlers.go
> +		panic(err.Error())
**[BLOCKER]** убрать использование паники

2023-10-17 10:33 UTC, akashipov commented on internal/server/handlers.go
> +		defer func() {
я только такое увидел как возможно обрабатывать панику. там идет каст значения в определенный тип через .(int64) например и никакой ошибки не возвращается. я предположил что там происходит паника, а значит нужно ее как то отловить через defer. Я попробовал и это сработало

2023-10-17 22:34 UTC, akashipov commented on internal/agent/metric_senders.go
> +	go r.PollIntervalCatch(donePollInterval)
это же запускается внутри for если был отловлен сигнал из этих функций нет? может я что то не понимаю

2023-10-17 22:35 UTC, akashipov commented on internal/agent/metric_senders.go
> +	go r.PollIntervalCatch(donePollInterval)
разве дед лока не будет если сначала ожидание а потом отправка?

2023-10-18 09:18 UTC, edylcrm requested changes

2023-10-18 09:18 UTC, edylcrm commented on cmd/agent/main.go
> +import (
```
func main() {

	srv := &http.Server{Handler: server.ServerRouter()}

	go func() {
		sigint := make(chan os.Signal, 1)
		signal.Notify(sigint, syscall.SIGINT, syscall.SIGTERM)
		sig := <-sigint
		fmt.Printf("Signal: %v\n", sig)

		// We received an interrupt signal, shut down.
		if err := srv.Shutdown(context.Background()); err != nil {
			// Error from closing listeners, or context timeout:
			log.Printf("HTTP server Shutdown: %v", err)
		}
	}()
	run(srv)
}

func run(srv *http.Server) {
	server.ParseArgsServer()
	srv.Addr = *server.HPServer
	fmt.Printf("Server is running on %s...\n", *server.HPServer)
	err := srv.ListenAndServe()
	if err != http.ErrServerClosed {
		log.Fatalf("HTTP server ListenAndServe: %v", err)
	}
}
```

2023-10-18 09:18 UTC, edylcrm commented on internal/agent/metric_senders.go
> +	go r.PollIntervalCatch(donePollInterval)
Ага, еще раз посмотрел, понял как работает, но написано не понятно, я бы тут переделал на time.NewTicker() и использовал его.
```
func (r *MetricSender) PollInterval(isTestMode bool) {
	memInfo := runtime.MemStats{}
	tickerPollInterval := time.NewTicker(time.Duration(*r.PollIntervalTime) * time.Second)
	tickerReportInterval := time.NewTicker(time.Duration(*r.ReportIntervalTime) * time.Second)
	countOfUpdate := 0
	for {
		select {
		case <-tickerPollInterval.C:
			runtime.ReadMemStats(&memInfo)
			countOfUpdate += 1
			fmt.Println("Done PollInterval!")
		case <-tickerReportInterval.C:
			r.ReportInterval(&memInfo, countOfUpdate)
			countOfUpdate = 0
			fmt.Println("Done ReportInterval!")
			if isTestMode {
				return
			}
		}
	}
}
```
Такой код читается намного проще

2023-10-18 09:18 UTC, edylcrm commented on internal/server/handlers.go
> +		defer func() {
А зачем обрабатывать панику? Бизнес логика не должна кидать паники

2023-10-18 09:45 UTC, akashipov commented on internal/server/handlers.go
> +		defer func() {
так там каст из interface{} -> int64 или interface{} -> float64 кидает панику, это не я кидаю

2023-10-18 09:46 UTC, akashipov commented on internal/server/handlers.go
> +		defer func() {
так там каст из interface{} -> int64 или interface{} -> float64 кидает панику, это не я кидаю же... я не знаю как это сделать по другому

2023-10-18 10:16 UTC, edylcrm requested changes

2023-10-18 10:16 UTC, edylcrm commented on internal/agent/metric_senders.go
> +	ticker := time.NewTicker(time.Second)
**[LINT]** этот ticker больше не нужен, можно удалить

2023-10-18 10:16 UTC, edylcrm commented on internal/agent/metric_senders.go
> +		return -2
**[BLOCKER]** это не С, в го нужно ориентироваться на ошибки. Давай переделаем мигнатуру метода на SendMetric(value interface{}, metricType string, metricName string) error

2023-10-18 10:16 UTC, edylcrm commented on internal/server/handlers.go
> +		defer func() {
**[BLOCKER]** Там где идет преобразование можно сделать:
```
iAreaId, ok := val.(int)
```
Тогда паника кидаться не будет, это более приоритетный вариант, Давай все таки переделаем

2023-10-18 11:57 UTC, edylcrm approved these changes

2023-10-19 07:53 UTC, merged