Iter9
akashipov/MetricCollector pull request #9
Opened 2023-11-01 23:56 UTC by akashipov

2023-11-02 08:31 UTC, edylcrm requested changes

2023-11-02 08:31 UTC, edylcrm commented on internal/server/handlers.go
> +		print(errors.New("wrong type of metric type"))
[LINT] print можно убрать

2023-11-02 08:31 UTC, edylcrm commented on internal/server/storages.go
> +	for _, val := range r.MetricList {
[BLOCKER] Здесь все таки стоит использовать map т.к. сложность поиска у нее O(1), в текущей реализации это O(n) т.е. если будет 1м записей, то нужно все пройти чтобы попробовать найти нужную запись которой может и не быть

2023-11-03 05:53 UTC, edylcrm approved these changes

2023-11-03 11:05 UTC, akashipov commented on internal/server/handlers.go
> +		print(errors.New("wrong type of metric type"))
удалил

2023-11-03 11:05 UTC, akashipov commented on internal/server/storages.go
> +	for _, val := range r.MetricList {
поправил на мапу для ускорения

2023-11-03 11:07 UTC, merged